#!/bin/sh

pushd $(dirname $(readlink -f "$BASH_SOURCE")) > /dev/null
ROOT_DIR=$(pwd)
popd > /dev/null

echo "source $ROOT_DIR/main.sh" >> ~/.bash_profile

echo "setlocal tabstop=4
setlocal softtabstop=4
setlocal shiftwidth=4
setlocal smarttab
setlocal expandtab" >> ~/.vimrc

echo "Install success!"
